from django.urls import path

from .views import (
    AuditLogView,
    CsrfView,
    DashboardView,
    DocumentDetailView,
    DocumentExtractionView,
    DocumentListCreateView,
    DocumentStatusView,
    DocumentUploadUrlView,
    DocumentUploadView,
    HealthView,
    LoginView,
    LogoutView,
    ReviewActionView,
    ReviewQueueView,
    ReviewSubmitView,
    SearchView,
    SemanticSearchView,
    SessionView,
    TokenRefreshView,
    TriggerReviewView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("auth/csrf/", CsrfView.as_view(), name="auth-csrf"),
    path("auth/me/", SessionView.as_view(), name="auth-me"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("documents/", DocumentListCreateView.as_view(), name="documents"),
    path("documents/upload-url/", DocumentUploadUrlView.as_view(), name="documents-upload-url"),
    path("documents/upload/", DocumentUploadView.as_view(), name="documents-upload"),
    path("documents/<str:document_id>/", DocumentDetailView.as_view(), name="document-detail"),
    path("documents/<str:document_id>/status/", DocumentStatusView.as_view(), name="document-status"),
    path("documents/<str:document_id>/extraction/", DocumentExtractionView.as_view(), name="document-extraction"),
    path("reviews/", ReviewQueueView.as_view(), name="reviews"),
    path("reviews/<str:document_id>/action/", ReviewActionView.as_view(), name="review-action"),
    path("reviews/<str:review_id>/submit/", ReviewSubmitView.as_view(), name="review-submit"),
    path("trigger-review/", TriggerReviewView.as_view(), name="trigger-review"),
    path("search/", SearchView.as_view(), name="search"),
    path("search/semantic/", SemanticSearchView.as_view(), name="search-semantic"),
    path("audit/<str:document_id>/", AuditLogView.as_view(), name="audit-logs"),
]
